clear all;close all;clc;

FilesToOpen = [{'Main2.m'}             ,{'MainInputData2.m'},...
               {'DatumTransmission.m'},{'DatumTransmissionInputData.m'},...
               {'DatumReception2.m'}   ,{'DatumReceptionInputData.m'},...
               {'DatumUpstream.m'}    ,{'DatumUpstreamInputData.m'},...
               {'DatumUpstrRec2.m'}    ,{'DatumUpstrRecInputData.m'}...
               ];
for kk=1:size(FilesToOpen,2)
    open(char(FilesToOpen(kk)))
end