clear all;close all;clc;
%%
FilesToOpen = [{'PlotingNoise.m'},{'Main.m'},{'MainInputData.m'},...
               {'OfdmInputData'},{'DatumTransmission.m'},...
               {'DatumTransmissionInputData.m'},{'DatumReception.m'},...
               {'DatumReceptionInputData.m'},{'DatumUpstream.m'},...
               {'DatumUpstreamInputData.m'},{'DatumUpstrRec.m'},...
               {'DatumUpstrRecInputData.m'},...
               {'DatumElectricReception.m'},...
               {'DatumElectricTransmission.m'},...
               {'FindChanelElectricalResponse.m'},...
               {'FindChanelResponse.m'}];
for kk=1:size(FilesToOpen,2)
    open(char(FilesToOpen(kk)))
end